require: rubocop-rspec

# Offense count: 1
Security/Eval:
  Exclude:
    - 'bin/*'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
