require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - utils/*
    - bin/*
    - doc/*
    - vendor/*
    - tmp/*

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['resource', 'describe', 'context']

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/Copyright:
  Notice: 'Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: "# Copyright (c) 2018 Danil Pismenny <danil@brandymint.ru>\n"
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: true
  VersionAdded: '0.30'
