# TODO move settings to Workers
#
AnalyticsWorker:
  cron: '*/5 * * * *'
  class: AnalyticsWorker
  queue: critical

ReconnectWorker:
  # NOTE Shecduled by SidekiqCronSetuper
  class: ReconnectWorker
  queue: critical

ScoresWatchDog:
  cron: '*/15 * * * *'
  class: ScoresWatchDog
  queue: critical
