ReconnectWorker:
  cron: '*/1 * * * *'
  class: ReconnectWorker
  queue: default

ScoreHistoryWorker:
  cron: '*/5 * * * *'
  class: ScoreHistoryWorker
  queue: default

PingRemoteNodesWorker:
  cron: '15 */1 * * *'
  class: PingRemoteNodesWorker
  queue: default
