AnalyticsWorker:
  cron: '*/5 * * * *'
  class: AnalyticsWorker
  queue: critical

ReconnectWorker:
  cron: '*/1 * * * *'
  class: ReconnectWorker
  queue: critical

ScoresWatchDog:
  cron: '*/15 * * * *'
  class: ScoresWatchDog
  queue: critical
