---
defaults: &defaults
  home: https://www.zold.io
  network: zold

  host: <%= ENV['ZOLD_HOST'] || `hostname -f` %>
  port: <%= ENV['ZOLD_POST'] || 4096 %>

  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  # @dapi`s invoice
  #
  invoice: <%= ENV['ZOLD_INVOICE'] || '66Yodh14@1142c2d008235bbe' %>

  redlock_redis:
    namespace: redlock
    url: redis://localhost:6379/8

  sidekiq_redis:
    # You can use a namespace if you have no empty dbs
    # namespace: zold
    url: redis://localhost:6379/8

  stores_dir: ./.data

  lock_timeout: 1000 # 1 second

  # Default remote nodes
  default_remotes:
    - 'b1.zold.io:80'
    - 'b2.zold.io:4096'
    - '159.203.63.90:4096'
    - '167.99.77.100:4096'
    - '159.203.19.189:4096'
    - '138.197.140.42:4096'

production:
  <<: *defaults

development:
  <<: *defaults
  stores_dir: ./.data/dev

test:
  <<: *defaults
  stores_dir: ./.data/test
  lock_timeout: 100 # 0.1 second
