:verbose: true
:concurrency: 8
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
production:
  :concurrency: 16
:queues:
  - [critical, 256]
  - [default, 1]
:logfile: ./log/sidekiq.log
