:verbose: true
:concurrency: 2
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
production:
  :concurrency: 4
:queues:
  - [worker0, 16]
  - [worker1, 16]
  - [worker2, 16]
  - [worker3, 16]
  - [default, 1]
:logfile: ./log/sidekiq.log
